/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ControllerMusicas;
import Controller.ControllerCurtida;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author unifbnascimento
 */
public class PaginaMusicas extends javax.swing.JFrame {

    /**
     * Creates new form PaginaBusca
     */
    public PaginaMusicas() {
        initComponents();
        c = new ControllerMusicas(this);
        d = new ControllerCurtida(this);
    }

    
    public JButton getBt_procurar_musica() {
        return bt_procurar_musica;
    }

    public void setBt_procurar_musica(JButton bt_procurar_musica) {
        this.bt_procurar_musica = bt_procurar_musica;
    }

    public JLabel getLb_buscar_musica() {
        return lb_buscar_musica;
    }

    public void setLb_buscar_musica(JLabel lb_buscar_musica) {
        this.lb_buscar_musica = lb_buscar_musica;
    }

    public JTextField getTxt_buscar_musica() {
        return txt_buscar_musica;
    }

    public void setTxt_buscar_musica(JTextField txt_buscar_musica) {
        this.txt_buscar_musica = txt_buscar_musica;
    }

    public JButton getBt_curtir() {
        return bt_curtir;
    }

    public void setBt_curtir(JButton bt_curtir) {
        this.bt_curtir = bt_curtir;
    }

    public JButton getBt_descurtir() {
        return bt_descurtir;
    }

    public void setBt_descurtir(JButton bt_descurtir) {
        this.bt_descurtir = bt_descurtir;
    }

    public JTextArea getTxt_area() {
        return txt_area;
    }

    public void setTxt_area(JTextArea txt_area) {
        this.txt_area = txt_area;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_buscar_musica = new javax.swing.JLabel();
        txt_buscar_musica = new javax.swing.JTextField();
        bt_procurar_musica = new javax.swing.JButton();
        bt_curtir = new javax.swing.JButton();
        bt_descurtir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lb_buscar_musica.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_buscar_musica.setForeground(new java.awt.Color(255, 0, 153));
        lb_buscar_musica.setText("O que deseja reproduzir?");

        txt_buscar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_musicaActionPerformed(evt);
            }
        });

        bt_procurar_musica.setBackground(new java.awt.Color(255, 0, 153));
        bt_procurar_musica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_procurar_musica.setText("Buscar");
        bt_procurar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_procurar_musicaActionPerformed(evt);
            }
        });

        bt_curtir.setBackground(new java.awt.Color(255, 0, 153));
        bt_curtir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_curtir.setText("Curtir");
        bt_curtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtirActionPerformed(evt);
            }
        });

        bt_descurtir.setBackground(new java.awt.Color(255, 0, 153));
        bt_descurtir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_descurtir.setText("Descurtir");
        bt_descurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtirActionPerformed(evt);
            }
        });

        txt_area.setBackground(new java.awt.Color(0, 0, 0));
        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane2.setViewportView(txt_area);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_descurtir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_buscar_musica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_procurar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_buscar_musica)
                    .addComponent(txt_buscar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_procurar_musica))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_descurtir)
                    .addComponent(bt_curtir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_musicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_musicaActionPerformed

    private void bt_procurar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_procurar_musicaActionPerformed
        // TODO add your handling code here:
        c.buscarMusica();
    }//GEN-LAST:event_bt_procurar_musicaActionPerformed

    private void bt_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtirActionPerformed
        // TODO add your handling code here:
        d.curtirMusica();
    }//GEN-LAST:event_bt_curtirActionPerformed

    private void bt_descurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtirActionPerformed
        // TODO add your handling code here:
        d.descurtirMusica();
    }//GEN-LAST:event_bt_descurtirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaginaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaginaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaginaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaginaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaginaBusca().setVisible(true);
//            }
//        });
//    }
    private ControllerMusicas c;
    private ControllerCurtida d;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_curtir;
    private javax.swing.JButton bt_descurtir;
    private javax.swing.JButton bt_procurar_musica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_buscar_musica;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_buscar_musica;
    // End of variables declaration//GEN-END:variables

}
