/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author unifbnascimento
 */
public class PaginaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PaginaMenu
     */
    public PaginaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bt_menu_biblioteca = new javax.swing.JButton();
        bt_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        bt_menu_biblioteca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt_menu_biblioteca.setForeground(new java.awt.Color(255, 0, 153));
        bt_menu_biblioteca.setText("Biblioteca");
        bt_menu_biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menu_bibliotecaActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_menu_biblioteca);

        bt_.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt_.setForeground(new java.awt.Color(255, 0, 153));
        bt_.setText("Fazer Casdastro");
        bt_.setFocusable(false);
        bt_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_menu_bibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menu_bibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_menu_bibliotecaActionPerformed

    private void bt_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_;
    private javax.swing.JButton bt_menu_biblioteca;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
