/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author unifbnascimento
 */
public class PaginaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form PaginaCadastro
     */
    public PaginaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_inscrever_spotifei = new javax.swing.JLabel();
        lb_cadastro_usuario = new javax.swing.JLabel();
        txt_cadastro_usuario = new javax.swing.JTextField();
        lb_cadastro_email = new javax.swing.JLabel();
        txt_cadastro_email = new javax.swing.JTextField();
        txt_cadastro_senha = new javax.swing.JPasswordField();
        lb_cadastro_email1 = new javax.swing.JLabel();
        lb_cadastro_senha = new javax.swing.JLabel();
        bt_cadastrar = new javax.swing.JButton();
        lb_cadastro_nome = new javax.swing.JLabel();
        txt_cadastro_nome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página de cadastro");

        lb_inscrever_spotifei.setFont(new java.awt.Font("Segoe UI", 3, 50)); // NOI18N
        lb_inscrever_spotifei.setForeground(new java.awt.Color(255, 0, 204));
        lb_inscrever_spotifei.setText("Inscreva-se no Spotifei");

        lb_cadastro_usuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_cadastro_usuario.setForeground(new java.awt.Color(255, 0, 204));
        lb_cadastro_usuario.setText("Nome de usuário*");

        txt_cadastro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadastro_usuarioActionPerformed(evt);
            }
        });

        lb_cadastro_email.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_cadastro_email.setForeground(new java.awt.Color(255, 0, 204));
        lb_cadastro_email.setText("Endereço de e-mail*");

        txt_cadastro_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadastro_emailActionPerformed(evt);
            }
        });

        lb_cadastro_email1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_cadastro_email1.setForeground(new java.awt.Color(255, 0, 204));

        lb_cadastro_senha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_cadastro_senha.setForeground(new java.awt.Color(255, 0, 204));
        lb_cadastro_senha.setText("Senha*");

        bt_cadastrar.setBackground(new java.awt.Color(255, 0, 153));
        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_cadastrar.setText("Cadastrar");

        lb_cadastro_nome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_cadastro_nome.setForeground(new java.awt.Color(255, 0, 204));
        lb_cadastro_nome.setText("Nome*");

        txt_cadastro_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadastro_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_inscrever_spotifei, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_cadastro_nome)
                            .addComponent(lb_cadastro_senha)
                            .addComponent(lb_cadastro_email)
                            .addComponent(lb_cadastro_usuario)
                            .addComponent(txt_cadastro_usuario)
                            .addComponent(txt_cadastro_email)
                            .addComponent(txt_cadastro_senha)
                            .addComponent(bt_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(txt_cadastro_nome))
                        .addGap(139, 139, 139))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(lb_cadastro_email1)
                    .addContainerGap(570, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lb_inscrever_spotifei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cadastro_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cadastro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lb_cadastro_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cadastro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cadastro_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cadastro_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cadastro_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cadastro_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(lb_cadastro_email1)
                    .addContainerGap(327, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cadastro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadastro_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadastro_usuarioActionPerformed

    private void txt_cadastro_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadastro_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadastro_emailActionPerformed

    private void txt_cadastro_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadastro_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadastro_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JLabel lb_cadastro_email;
    private javax.swing.JLabel lb_cadastro_email1;
    private javax.swing.JLabel lb_cadastro_nome;
    private javax.swing.JLabel lb_cadastro_senha;
    private javax.swing.JLabel lb_cadastro_usuario;
    private javax.swing.JLabel lb_inscrever_spotifei;
    private javax.swing.JTextField txt_cadastro_email;
    private javax.swing.JTextField txt_cadastro_nome;
    private javax.swing.JPasswordField txt_cadastro_senha;
    private javax.swing.JTextField txt_cadastro_usuario;
    // End of variables declaration//GEN-END:variables
}
