/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ControllerPlaylist;
import javax.swing.*;
import java.awt.event.*;


/**
 *
 * @author bianc
 */
public class PaginaPlaylist extends javax.swing.JFrame {
    private int idUsuario;

    /**
     * Creates new form PaginaPlaylist
     */
    public PaginaPlaylist() {
        initComponents();
        c = new ControllerPlaylist(this, idUsuario);

    }

    public JButton getBt_criar_playlist() {
        return bt_criar_playlist;
    }

    public void setBt_criar_playlist(JButton bt_criar_playlist) {
        this.bt_criar_playlist = bt_criar_playlist;
    }

    public JButton getBt_pesquisar_playlist() {
        return bt_listar_playlist;
    }

    public void setBt_pesquisar_playlist(JButton bt_pesquisar_playlist) {
        this.bt_listar_playlist = bt_pesquisar_playlist;
    }

    public JLabel getLbl_biblioteca() {
        return lbl_biblioteca;
    }

    public void setLbl_biblioteca(JLabel lbl_biblioteca) {
        this.lbl_biblioteca = lbl_biblioteca;
    }

    public JTextArea getTxt_area_playlist() {
        return txt_area_playlist;
    }

    public void setTxt_area_playlist(JTextArea txt_area_playlist) {
        this.txt_area_playlist = txt_area_playlist;
    }

    public JButton getBt_listar_playlist() {
        return bt_listar_playlist;
    }

    public void setBt_listar_playlist(JButton bt_listar_playlist) {
        this.bt_listar_playlist = bt_listar_playlist;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_biblioteca = new javax.swing.JLabel();
        bt_criar_playlist = new javax.swing.JButton();
        bt_listar_playlist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_playlist = new javax.swing.JTextArea();
        bt_remover_musica = new javax.swing.JButton();
        bt_adicionar_musica = new javax.swing.JButton();
        bt_remover_playlist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl_biblioteca.setBackground(new java.awt.Color(0, 0, 0));
        lbl_biblioteca.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lbl_biblioteca.setForeground(new java.awt.Color(255, 0, 153));
        lbl_biblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_biblioteca.setText("Biblioteca");
        lbl_biblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bt_criar_playlist.setBackground(new java.awt.Color(255, 0, 153));
        bt_criar_playlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_criar_playlist.setText("Criar playlist");
        bt_criar_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criar_playlistActionPerformed(evt);
            }
        });

        bt_listar_playlist.setBackground(new java.awt.Color(255, 0, 153));
        bt_listar_playlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_listar_playlist.setText("Listar playlists");
        bt_listar_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listar_playlistActionPerformed(evt);
            }
        });

        txt_area_playlist.setBackground(new java.awt.Color(0, 0, 0));
        txt_area_playlist.setColumns(20);
        txt_area_playlist.setForeground(new java.awt.Color(255, 0, 153));
        txt_area_playlist.setRows(5);
        jScrollPane1.setViewportView(txt_area_playlist);

        bt_remover_musica.setBackground(new java.awt.Color(255, 0, 153));
        bt_remover_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover_musica.setText("Remover música");
        bt_remover_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remover_musicaActionPerformed(evt);
            }
        });

        bt_adicionar_musica.setBackground(new java.awt.Color(255, 0, 153));
        bt_adicionar_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_adicionar_musica.setText("Adicionar música");
        bt_adicionar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionar_musicaActionPerformed(evt);
            }
        });

        bt_remover_playlist.setBackground(new java.awt.Color(255, 0, 153));
        bt_remover_playlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover_playlist.setText("Excluir playlist");
        bt_remover_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remover_playlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_criar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_listar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_remover_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_adicionar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_remover_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbl_biblioteca)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_criar_playlist)
                            .addComponent(bt_adicionar_musica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_remover_playlist)
                            .addComponent(bt_remover_musica))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bt_listar_playlist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_listar_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listar_playlistActionPerformed
        // TODO add your handling code here:
        c.listarPlaylists();
    }//GEN-LAST:event_bt_listar_playlistActionPerformed

    private void bt_criar_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criar_playlistActionPerformed
        // TODO add your handling code here:
        c.criarPlaylist();
    }//GEN-LAST:event_bt_criar_playlistActionPerformed

    private void bt_remover_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remover_musicaActionPerformed
        // TODO add your handling code here:
        c.removerMusicaDaPlaylist();
    }//GEN-LAST:event_bt_remover_musicaActionPerformed

    private void bt_adicionar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionar_musicaActionPerformed
        // TODO add your handling code here:
        c.adicionarMusicaNaPlaylist();
    }//GEN-LAST:event_bt_adicionar_musicaActionPerformed

    private void bt_remover_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remover_playlistActionPerformed
        // TODO add your handling code here:
        c.excluirPlaylist();
    }//GEN-LAST:event_bt_remover_playlistActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaginaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaginaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaginaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaginaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaginaPlaylist().setVisible(true);
//            }
//        });
//    }
    private ControllerPlaylist c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar_musica;
    private javax.swing.JButton bt_criar_playlist;
    private javax.swing.JButton bt_listar_playlist;
    private javax.swing.JButton bt_remover_musica;
    private javax.swing.JButton bt_remover_playlist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_biblioteca;
    private javax.swing.JTextArea txt_area_playlist;
    // End of variables declaration//GEN-END:variables
}
