/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Usuario;
import Controller.ControllerLogin;

/**
 *
 * @author unifbnascimento
 */
public class PaginaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PaginaLogin
     */
    public PaginaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_spotifei = new javax.swing.JLabel();
        lb_login_usuario = new javax.swing.JLabel();
        txt_login_usuario = new javax.swing.JTextField();
        lb_login_senha = new javax.swing.JLabel();
        lbl_nao_tem_conta = new javax.swing.JLabel();
        bt_entrar = new javax.swing.JButton();
        lbl_esqueceu_senha = new javax.swing.JLabel();
        lbl_inscrever = new javax.swing.JLabel();
        txt_login_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página de Login");
        setBackground(new java.awt.Color(0, 0, 0));

        lb_spotifei.setFont(new java.awt.Font("Segoe UI", 3, 50)); // NOI18N
        lb_spotifei.setForeground(new java.awt.Color(255, 0, 204));
        lb_spotifei.setText("Spotifei");

        lb_login_usuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_login_usuario.setForeground(new java.awt.Color(255, 0, 204));
        lb_login_usuario.setText("E-mail ou nome de usuário");

        txt_login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_usuarioActionPerformed(evt);
            }
        });

        lb_login_senha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_login_senha.setForeground(new java.awt.Color(255, 0, 204));
        lb_login_senha.setText("Senha:");

        lbl_nao_tem_conta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_nao_tem_conta.setForeground(new java.awt.Color(255, 0, 204));
        lbl_nao_tem_conta.setText("Não tem conta?");

        bt_entrar.setBackground(new java.awt.Color(255, 0, 153));
        bt_entrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });

        lbl_esqueceu_senha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_esqueceu_senha.setForeground(new java.awt.Color(255, 0, 204));
        lbl_esqueceu_senha.setText("Esqueceu a senha?");

        lbl_inscrever.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_inscrever.setForeground(new java.awt.Color(255, 0, 204));
        lbl_inscrever.setText("Inscrever-se no Spotifei");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_spotifei, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_login_senha)
                            .addComponent(lb_login_usuario)
                            .addComponent(txt_login_usuario)
                            .addComponent(bt_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txt_login_senha))
                        .addContainerGap(186, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lbl_nao_tem_conta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lbl_esqueceu_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lb_spotifei)
                .addGap(39, 39, 39)
                .addComponent(lb_login_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_login_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(bt_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_esqueceu_senha)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nao_tem_conta)
                    .addComponent(lbl_inscrever))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_usuarioActionPerformed

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaginaLogin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JLabel lb_login_senha;
    private javax.swing.JLabel lb_login_usuario;
    private javax.swing.JLabel lb_spotifei;
    private javax.swing.JLabel lbl_esqueceu_senha;
    private javax.swing.JLabel lbl_inscrever;
    private javax.swing.JLabel lbl_nao_tem_conta;
    private javax.swing.JPasswordField txt_login_senha;
    private javax.swing.JTextField txt_login_usuario;
    // End of variables declaration//GEN-END:variables
}
