/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
/**
 *
 * @author bianc
 */
public class PaginaHistorico extends javax.swing.JFrame {

    /**
     * Creates new form PaginaHistorico
     */
    public PaginaHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpl_historico_01 = new javax.swing.JPanel();
        jpl_historico_02 = new javax.swing.JPanel();
        jpl_historico_03 = new javax.swing.JPanel();
        jpl_historico_04 = new javax.swing.JPanel();
        jpl_historico_05 = new javax.swing.JPanel();
        jpl_historico_06 = new javax.swing.JPanel();
        jpl_historico_07 = new javax.swing.JPanel();
        jpl_historico_08 = new javax.swing.JPanel();
        jpl_historico_09 = new javax.swing.JPanel();
        jpl_historico_10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        lbl_historico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jpl_historico_01.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_01.setPreferredSize(new java.awt.Dimension(598, 80));

        javax.swing.GroupLayout jpl_historico_01Layout = new javax.swing.GroupLayout(jpl_historico_01);
        jpl_historico_01.setLayout(jpl_historico_01Layout);
        jpl_historico_01Layout.setHorizontalGroup(
            jpl_historico_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jpl_historico_01Layout.setVerticalGroup(
            jpl_historico_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_02.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_02.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_02Layout = new javax.swing.GroupLayout(jpl_historico_02);
        jpl_historico_02.setLayout(jpl_historico_02Layout);
        jpl_historico_02Layout.setHorizontalGroup(
            jpl_historico_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_02Layout.setVerticalGroup(
            jpl_historico_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_03.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_03.setPreferredSize(new java.awt.Dimension(598, 80));

        javax.swing.GroupLayout jpl_historico_03Layout = new javax.swing.GroupLayout(jpl_historico_03);
        jpl_historico_03.setLayout(jpl_historico_03Layout);
        jpl_historico_03Layout.setHorizontalGroup(
            jpl_historico_03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_03Layout.setVerticalGroup(
            jpl_historico_03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_04.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_04.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_04Layout = new javax.swing.GroupLayout(jpl_historico_04);
        jpl_historico_04.setLayout(jpl_historico_04Layout);
        jpl_historico_04Layout.setHorizontalGroup(
            jpl_historico_04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_04Layout.setVerticalGroup(
            jpl_historico_04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_05.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_05.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_05Layout = new javax.swing.GroupLayout(jpl_historico_05);
        jpl_historico_05.setLayout(jpl_historico_05Layout);
        jpl_historico_05Layout.setHorizontalGroup(
            jpl_historico_05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_05Layout.setVerticalGroup(
            jpl_historico_05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_06.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_06.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_06Layout = new javax.swing.GroupLayout(jpl_historico_06);
        jpl_historico_06.setLayout(jpl_historico_06Layout);
        jpl_historico_06Layout.setHorizontalGroup(
            jpl_historico_06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_06Layout.setVerticalGroup(
            jpl_historico_06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_07.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_07.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_07Layout = new javax.swing.GroupLayout(jpl_historico_07);
        jpl_historico_07.setLayout(jpl_historico_07Layout);
        jpl_historico_07Layout.setHorizontalGroup(
            jpl_historico_07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_07Layout.setVerticalGroup(
            jpl_historico_07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_08.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_08.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_08Layout = new javax.swing.GroupLayout(jpl_historico_08);
        jpl_historico_08.setLayout(jpl_historico_08Layout);
        jpl_historico_08Layout.setHorizontalGroup(
            jpl_historico_08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_08Layout.setVerticalGroup(
            jpl_historico_08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_09.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_09.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_09Layout = new javax.swing.GroupLayout(jpl_historico_09);
        jpl_historico_09.setLayout(jpl_historico_09Layout);
        jpl_historico_09Layout.setHorizontalGroup(
            jpl_historico_09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_09Layout.setVerticalGroup(
            jpl_historico_09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpl_historico_10.setBackground(new java.awt.Color(51, 51, 51));
        jpl_historico_10.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout jpl_historico_10Layout = new javax.swing.GroupLayout(jpl_historico_10);
        jpl_historico_10.setLayout(jpl_historico_10Layout);
        jpl_historico_10Layout.setHorizontalGroup(
            jpl_historico_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpl_historico_10Layout.setVerticalGroup(
            jpl_historico_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jScrollBar1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jScrollBar1);

        lbl_historico.setBackground(new java.awt.Color(0, 0, 0));
        lbl_historico.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lbl_historico.setForeground(new java.awt.Color(255, 0, 153));
        lbl_historico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_historico.setText("Histórico");
        lbl_historico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpl_historico_01, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_02, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_03, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_05, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_06, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_07, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_08, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_09, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_10, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jpl_historico_04, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(lbl_historico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_historico)
                        .addGap(28, 28, 28)
                        .addComponent(jpl_historico_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpl_historico_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaHistorico().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpl_historico_01;
    private javax.swing.JPanel jpl_historico_02;
    private javax.swing.JPanel jpl_historico_03;
    private javax.swing.JPanel jpl_historico_04;
    private javax.swing.JPanel jpl_historico_05;
    private javax.swing.JPanel jpl_historico_06;
    private javax.swing.JPanel jpl_historico_07;
    private javax.swing.JPanel jpl_historico_08;
    private javax.swing.JPanel jpl_historico_09;
    private javax.swing.JPanel jpl_historico_10;
    private javax.swing.JLabel lbl_historico;
    // End of variables declaration//GEN-END:variables
}
